### ISSUE TITLE
Add support for ESLint flat config

### ISSUE THREAD

**Issue by mheob** [sanity-io/eslint-config-studio#39]
## Is your feature request related to a problem?

ESLint has changed the default configuration style to [flat config](https://eslint.org/docs/latest/use/configure/configuration-files). Currently this extension does not work immediately.

## Describe the solution you'd like

To use this extension in the latest ESLint versions, it should support flat config. A [migration guide](https://eslint.org/docs/latest/use/configure/migration-guide) is provided by ESLint.

**Comment by lentilz** [comment]
Attempts at using this with [Flat Compat](https://github.com/eslint/eslintrc?tab=readme-ov-file#usage-esm) returns the below error:
```
Error: Key "plugins": Cannot redefine plugin "react" at .../sanity-cms/node_modules/@humanwhocodes/object-schema/src/object-schema.js:250:27
```

eslint.config.js settings tried the below with the same error each time
1. `...compat.extends("@sanity/eslint-config-studio")`
2. `...compat.extends(resolve(__dirname, "node_modules/@sanity/eslint-config-studio")),`

**Comment by rexxars** [comment]
[v5](https://github.com/sanity-io/eslint-config-studio/releases/tag/v5.0.0) uses the new flat config style 👍
